type Well {
  id: ID!
  name: String!
  location: Location!
}

type DrillingReport {
  id: ID!
  well: Well!
  date: String!
  comment: String!
  drillingProblem: DrillingProblem
}

type Location {
  id: ID!
  lat: String!
  long: String!
}

type DrillingProblem {
  id: ID!
  name: String
  problemType: String!
}

type ExpectedDrillingProblem {
  id: ID!
  probability: String!
  drillingProblem: DrillingProblem!
}

type NearbyWell {
  id: ID!
  well: Well!
  distance: String!
}
